---

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  # VM_HOST Pool:
  VM_START_NUM: "001"
  VM_END_NUM: "016"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - pre-test
  - test

unittests-build-job:
  tags: [vm_host, x86_64]
  stage: pre-test
  variables:
  parallel:
    matrix:
      - BUILD_TYPE: verbs-debug
        FLAGS: --with-rdma --enable-debug --enable-werror
      - BUILD_TYPE: mlx5_dv-debug
        FLAGS: --with-rdma=mlx5_dv --enable-debug --enable-werror
      - BUILD_TYPE: mlx5_dv-release
        FLAGS: --with-rdma=mlx5_dv --enable-werror
  script:
    - ./configure ${FLAGS} --with-crypto --with-vfio-user --with-xlio --with-shared
    - make -j4
    - ./test/unit/unittest.sh

.autotest-template:
  tags: [vm_host, x86_64]
  stage: test
  before_script:
    - .ci/prepare_vm.sh
  after_script:
    - tar czf $CI_PROJECT_DIR/${TEST_TYPE}_artifacts.tar -C $CI_PROJECT_DIR/.. output
  artifacts:
    name: ${TEST_TYPE}_artifacts

autotest-nvmf-tcp:
  extends: .autotest-template
  variables:
    TEST_TYPE: nvmf-tcp
  script:
    - ./configure --enable-debug --without-idxd --with-rdma --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-coverage --with-ublk --with-xlio && make -j${nproc}
    - ./autorun.sh .ci/autotest-${TEST_TYPE}.conf

autotest-vm_host-matrix:
  extends: .autotest-template
  parallel:
    matrix:
      - TEST_TYPE: [nvme, accel, fsdev, bdev, nvmf-rdma]
  script:
    - ./autorun.sh .ci/autotest-${TEST_TYPE}.conf

test-crypto-job:
  extends: .autotest-template
  variables:
    # VMs 17-20 have BlueField3 vfs with crypto
    VM_START_NUM: "017"
    VM_END_NUM: "020"
    CI_DUT_RDMA: "mlx5_0"
    TEST_TYPE: crypto
  script:
    - ./configure --enable-debug --with-rdma=mlx5_dv --with-crypto
    - make -j${nproc}
    - ./scripts/setup.sh
    - ./test/accel/mlx5/accel_mlx5_crypto_key_upper_lba.sh --allowed-devs=${CI_DUT_RDMA}
    - ./test/accel/mlx5/accel_mlx5_crypto.sh --allowed-devs=${CI_DUT_RDMA}
    - ./test/accel/mlx5/accel_mlx5_crypto.sh --allowed-devs=${CI_DUT_RDMA} --transport=rdma

coverity-job:
  tags: [k8s, linux, x86_64]
  stage: test
  image: "$COV_IMAGE"
  script:
    - apt-get -q update
    - ./scripts/pkgdep.sh
    - ./configure --with-rdma=mlx5_dv --disable-unit-tests
    - cov-build --dir cov_build make -j 4
    - cov-analyze --jobs auto --security --concurrency --dir cov_build
    - cov-format-errors --dir cov_build --html-output cov_build/html
    - nr=$(cov-format-errors --dir cov_build |& awk '/Processing [0-9]+ errors?/ { print $2 }')
    - exit $nr
  variables:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/cov/bin
    CC: gcc-9
  allow_failure: true
  artifacts:
    name: coverity
    paths:
      - cov_build/html/
    expire_in: 1 week
    when: always

code-style-job:
  tags: [vm_host, x86_64]
  stage: pre-test
  script:
    - ./scripts/check_format.sh

autobuild-check-so-deps-job:
  extends: .autotest-template
  variables:
    TEST_TYPE: autobuild
  script:
    - ./autorun.sh .ci/autotest-${TEST_TYPE}.conf
    - ./configure --with-rdma=mlx5_dv --enable-debug --enable-werror --with-shared && make -j8
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Mellanox/spdk_team/spdk-abi.git test/make/abi
    - sudo ./test/make/check_so_deps.sh

test-virtio-fs-app:
  stage: test
  tags: [vm_host, x86_64]
  variables:
    VIRTIO_FS_TARGET_REF: main
  script:
    - .ci/run_virtio_fs_app.sh
  dependencies: []
  artifacts:
    when: always
    paths:
      - trigger.json
      - pipeline.json
