---

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  # VM_HOST Pool:
  VM_START_NUM: "001"
  VM_END_NUM: "016"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - pre-test
  - test
  - post-test

.autotest-template:
  tags: [vm_host, x86_64]
  stage: test
  before_script:
    - .ci/prepare_vm.sh
  after_script:
    - tar czf $CI_PROJECT_DIR/${TEST_TYPE}_artifacts.tar.gz -C $CI_PROJECT_DIR/../output .
  artifacts:
    name: ${TEST_TYPE}_artifacts
    paths:
      - $CI_PROJECT_DIR/${TEST_TYPE}_artifacts.tar.gz
    expire_in: 3 days
    when: always

unittests-build-job:
  extends: .autotest-template
  stage: pre-test
  parallel:
    matrix:
      - BUILD_TYPE: verbs-debug
        FLAGS: --with-rdma --enable-debug --enable-werror
      - BUILD_TYPE: mlx5_dv-debug
        FLAGS: --with-rdma=mlx5_dv --enable-debug --enable-werror
      - BUILD_TYPE: mlx5_dv-release
        FLAGS: --with-rdma=mlx5_dv --enable-werror
  script:
    - ./configure ${FLAGS} --with-crypto --with-vfio-user --with-xlio --with-shared && make -j8
    - ./autotest.sh .ci/autotest-unittests.conf

autotest-vm_host-matrix:
  extends: .autotest-template
  parallel:
    matrix:
      - TEST_TYPE: [nvme, accel, fsdev, bdev, nvmf-rdma, nvmf-tcp, autobuild-check-so]
  script:
    - ./autorun.sh .ci/autotest-${TEST_TYPE}.conf
    - |
      if [ "$TEST_TYPE" = "autobuild-check-so" ]; then
        git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/spdk_team/spdk-abi.git test/make/abi
        test/make/check_so_deps.sh -c .ci/autotest-autobuild-check-so.conf -a test/make/abi
      fi

test-crypto-job:
  extends: .autotest-template
  variables:
    # VMs 17-20 have BlueField3 vfs with crypto
    VM_START_NUM: "017"
    VM_END_NUM: "020"
    TEST_TYPE: crypto
    SPDK_TEST_NVMF_NICS: mlx5
  script:
    - ./configure --enable-debug  --with-rdma=mlx5_dv --with-crypto --enable-werror --without-idxd --with-fio=/usr/src/fio --enable-ubsan --enable-asan --enable-coverage --with-ublk --with-shared && make -j${nproc}
    - ./scripts/setup.sh
    - ./test/accel/mlx5/accel_mlx5_crypto.sh

coverity-job:
  tags: [vm_host, x86_64]
  stage: test
  script:
    - .ci/run_coverity.sh
  allow_failure: true
  artifacts:
    name: coverity
    paths:
      - cov_build/html/
    expire_in: 1 week
    when: always

code-style-job:
  tags: [vm_host, x86_64]
  stage: pre-test
  script:
    - ./scripts/check_format.sh

test-virtio-fs-app:
  stage: test
  tags: [vm_host, x86_64]
  parallel:
    matrix:
      - VIRTIO_FS_TARGET_REF: [main, cmx_target_alpha]
  script:
    - .ci/run_virtio_fs_app.sh
  dependencies: []
  artifacts:
    when: always
    paths:
      - trigger.json
      - pipeline.json

test-cmx-target:
  stage: test
  trigger:
    project: spdk_team/cmx-target
    branch: main
    strategy: depend
  variables:
    SPDK_REVISION: ${CI_COMMIT_SHA}
    SPDK_REMOTE: ${SPDK_INTERNAL_REPO_URL}

autotest-summary-job:
  stage: post-test
  tags: [vm_host, x86_64]
  variables:
      GIT_SUBMODULE_STRATEGY: none
  needs:
    - job: autotest-vm_host-matrix
      artifacts: true
    - job: test-crypto-job
      artifacts: true
  script:
    - .ci/autotest_summary.sh
  artifacts:
    name: autotest_summary_artifacts
    paths:
      - $CI_PROJECT_DIR/autotest_summary
    expire_in: 1 week
    when: always
