#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../../..)

TEST_FILE = hybrid_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
