SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_NVMF=1
SPDK_TEST_NVME_CLI=1
SPDK_TEST_NVMF_TRANSPORT=rdma
SPDK_TEST_RDMA_PROV=mlx5_dv
SPDK_TEST_NVMF_NICS=mlx5
#SPDK_TEST_USDT=1 #Temporary disabled
SPDK_TEST_NVMF_MDNS=1
SPDK_RUN_UBSAN=1
SPDK_RUN_ASAN=1
NET_TYPE=phy
