#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)

TEST_FILE = fuse_dispatcher_ut.c

SPDK_LIB_LIST = fuse_dispatcher

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
